# Generated by Django 3.2.16 on 2023-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keshihua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case_item',
            name='url',
            field=models.CharField(default='', max_length=240, verbose_name='链接'),
        ),
    ]
